INSERT INTO CURRENCY_EXCHANGE(ID, CURRENCY_FROM, CURRENCY_TO, CONVERSION_MULTIPLE, ENVIROMENT) VALUES(10001, 'USD', 'EUR', 2, ' ')
INSERT INTO CURRENCY_EXCHANGE(ID, CURRENCY_FROM, CURRENCY_TO, CONVERSION_MULTIPLE, ENVIROMENT) VALUES(10002, 'USD', 'PST', 21, ' ')
INSERT INTO CURRENCY_EXCHANGE(ID, CURRENCY_FROM, CURRENCY_TO, CONVERSION_MULTIPLE, ENVIROMENT) VALUES(10003, 'USD', 'IND', 62, ' ')